apiVersion: apps/v1
kind: Deployment
metadata:
  name: customermanagementdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CustomerManagement
  template:
    metadata:
      labels:
        app: CustomerManagement
    spec:
      containers:
      - name: dockersamplerepos
        image: vjcustreg.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn
---
apiVersion: v1
kind: Service
metadata:
  name: customermanagementservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: CustomerManagement